name: Tests and coverage
on: [push]
jobs:
  tests-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./api/package-lock.json"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
